# Generated by Django 4.2.13 on 2024-07-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Attraction", "0007_alter_attraction_comment_count_and_more"),
        ("Tourist", "0004_alter_tourist_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourist",
            name="points",
            field=models.IntegerField(default=0, verbose_name="积分"),
        ),
        migrations.CreateModel(
            name="FavoriteAttraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="Attraction.attraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_attractions",
                        to="Tourist.tourist",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏景点",
                "verbose_name_plural": "收藏景点",
                "unique_together": {("user", "attraction")},
            },
        ),
    ]
