# Generated by Django 4.2.13 on 2024-07-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Attraction", "0007_alter_attraction_comment_count_and_more"),
        ("Tourist", "0005_tourist_points_favoriteattraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoriteattraction",
            name="attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="Attraction.attraction",
                verbose_name="景点",
            ),
        ),
        migrations.AlterField(
            model_name="favoriteattraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="Tourist.tourist",
                verbose_name="用户",
            ),
        ),
    ]
