# Generated by Django 4.2.13 on 2024-07-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tourist", "0006_alter_favoriteattraction_attraction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourist",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default_avatar.jpg",
                null=True,
                upload_to="avatars/",
                verbose_name="头像",
            ),
        ),
    ]
