# Generated by Django 5.0.6 on 2024-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rt_Rq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rt_rq',
            name='limit',
            field=models.PositiveIntegerField(default=30, verbose_name='人数限制'),
        ),
    ]
