# Generated by Django 4.2.13 on 2024-07-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attraction", "0006_remove_comment_optional_image_commentimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="comment_count",
            field=models.IntegerField(default=0, verbose_name="评论数"),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="评分"
            ),
        ),
    ]
